### ISSUE TITLE
Got the following error in extraction while extrating kohli's video

### ISSUE THREAD

**Issue by Adityaraj975** [Adityaraj975/DFL#1]
Error while processing data: Traceback (most recent call last):
  File "/content/DeepFaceLab/core/joblib/SubprocessorBase.py", line 71, in _subprocess_run
    result = self.process_data (data)
  File "/content/DeepFaceLab/mainscripts/Extractor.py", line 169, in process_data
    cv2_imwrite(output_filepath, face)
  File "/content/DeepFaceLab/core/cv2ex.py", line 26, in cv2_imwrite
    ret, buf = cv2.imencode( Path(filename).suffix, img, *args)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgcodecs/src/grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'throwOnEror'

**Comment by Adityaraj975** [comment]
Solved. 
Added an if statement to check if any of the face dimensions are zero, if yes then it doesn't go for cv2_imwrite. 
This error raised because one of the dimensions of the face was zero, which was because of the face detector.
